# Generated by Django 5.2.7 on 2025-10-02 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='username',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['email'], name='core_loginl_email_2d9c43_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['success'], name='core_loginl_success_0b884d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['created_at'], name='core_loginl_created_110d4e_idx'),
        ),
    ]
