# Generated by Django 5.2.7 on 2025-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_documentos_satregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='satregistro',
            name='data_emissao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
