# Generated by Django 5.2.7 on 2025-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_satregistro_data_emissao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='satregistro',
            name='uniq_empresa_sheet_row',
        ),
        migrations.AddField(
            model_name='satregistro',
            name='competencia',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='satregistro',
            index=models.Index(fields=['empresa', 'competencia'], name='core_satreg_empresa_5782d3_idx'),
        ),
        migrations.AddIndex(
            model_name='satregistro',
            index=models.Index(fields=['empresa', 'data_emissao'], name='core_satreg_empresa_52c474_idx'),
        ),
        migrations.AddConstraint(
            model_name='satregistro',
            constraint=models.UniqueConstraint(condition=models.Q(('competencia__isnull', True), _negated=True), fields=('empresa', 'competencia', 'sheet', 'row'), name='uniq_emp_comp_sheet_row'),
        ),
    ]
